/**
 * API 에러 코드.
 * 프론트엔드가 이 코드로 분기하므로 값을 임의로 바꾸지 마세요.
 */
export const ERROR_CODES = {
  // 인증 / 권한
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PROFILE_REQUIRED: "PROFILE_REQUIRED",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  INVALID_OAUTH_CODE: "INVALID_OAUTH_CODE",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  INVALID_OR_EXPIRED_SIGNUP_TOKEN: "INVALID_OR_EXPIRED_SIGNUP_TOKEN",
  PROVIDER_ACCOUNT_ALREADY_LINKED: "PROVIDER_ACCOUNT_ALREADY_LINKED",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",

  // 비밀번호 재설정
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_ATTEMPTS_EXCEEDED: "RESET_CODE_ATTEMPTS_EXCEEDED",
  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",

  // 회원가입 이메일 인증 (비밀번호 재설정과 별개)
  INVALID_SIGNUP_CODE: "INVALID_SIGNUP_CODE",
  SIGNUP_CODE_EXPIRED: "SIGNUP_CODE_EXPIRED",
  SIGNUP_CODE_ATTEMPTS_EXCEEDED: "SIGNUP_CODE_ATTEMPTS_EXCEEDED",
  /** 인증 이력이 없거나 인증 후 30분이 지남. 인증번호를 다시 받아야 합니다 */
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // 견적 요청
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REQUEST_EXISTS",
  NO_ACTIVE_REQUEST: "NO_ACTIVE_REQUEST",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ALREADY_TARGETED: "ALREADY_TARGETED",

  // 견적
  ESTIMATE_LIMIT_EXCEEDED: "ESTIMATE_LIMIT_EXCEEDED",
  ALREADY_ESTIMATED: "ALREADY_ESTIMATED",
  NOT_SERVICE_REGION: "NOT_SERVICE_REGION",
  ESTIMATE_ALREADY_PROCESSED: "ESTIMATE_ALREADY_PROCESSED",

  // 리뷰
  REVIEW_ALREADY_CONFIRMED: "REVIEW_ALREADY_CONFIRMED",

  // 찜
  ALREADY_FAVORITED: "ALREADY_FAVORITED",

  // 채팅
  /** 이사 완료 후 14일이 지난 방 — 지난 대화는 볼 수 있지만 보낼 수는 없습니다 */
  CHAT_ROOM_CLOSED: "CHAT_ROOM_CLOSED",

  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  /** 봇 검증(Turnstile) 토큰이 없거나 틀렸을 때. 위젯을 다시 풀고 재시도하면 됩니다 */
  BOT_CHECK_FAILED: "BOT_CHECK_FAILED",
  /** Serializable 트랜잭션 재시도를 모두 소진했을 때. 잠시 후 재시도하면 됩니다 */
  CONCURRENT_REQUEST_CONFLICT: "CONCURRENT_REQUEST_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
