/**
 * API 에러 코드.
 * 프론트엔드가 이 코드로 분기하므로 값을 임의로 바꾸지 마세요.
 */
export const ERROR_CODES = {
  // 인증 / 권한
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PROFILE_REQUIRED: "PROFILE_REQUIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",

  // 견적 요청
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REQUEST_EXISTS",
  NO_ACTIVE_REQUEST: "NO_ACTIVE_REQUEST",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ALREADY_TARGETED: "ALREADY_TARGETED",

  // 견적
  ESTIMATE_LIMIT_EXCEEDED: "ESTIMATE_LIMIT_EXCEEDED",
  ALREADY_ESTIMATED: "ALREADY_ESTIMATED",
  NOT_SERVICE_REGION: "NOT_SERVICE_REGION",
  ESTIMATE_ALREADY_PROCESSED: "ESTIMATE_ALREADY_PROCESSED",

  // 찜
  ALREADY_FAVORITED: "ALREADY_FAVORITED",

  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  /** Serializable 트랜잭션 재시도를 모두 소진했을 때. 잠시 후 재시도하면 됩니다 */
  CONCURRENT_REQUEST_CONFLICT: "CONCURRENT_REQUEST_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
