/**
 * API 에러 코드.
 * 프론트엔드가 이 코드로 분기하므로 값을 임의로 바꾸지 마세요.
 */
export const ERROR_CODES = {
  // 인증 / 권한
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PROFILE_REQUIRED: "PROFILE_REQUIRED",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  INVALID_OAUTH_CODE: "INVALID_OAUTH_CODE",
  OAUTH_PROVIDER_ERROR: "OAUTH_PROVIDER_ERROR",
  INVALID_OR_EXPIRED_SIGNUP_TOKEN: "INVALID_OR_EXPIRED_SIGNUP_TOKEN",
  PROVIDER_ACCOUNT_ALREADY_LINKED: "PROVIDER_ACCOUNT_ALREADY_LINKED",
  OAUTH_EMAIL_REQUIRED: "OAUTH_EMAIL_REQUIRED",
  /** 확정된 이사(고객 ASSIGNED 요청·기사님 CONFIRMED 견적)가 남아 탈퇴 불가. 이사일 다음 날 완료 처리되면 탈퇴할 수 있습니다 */
  CONFIRMED_MOVE_EXISTS: "CONFIRMED_MOVE_EXISTS",
  /** 이사는 끝났지만 잔금 결제가 끝나지 않은 견적(COMPLETED + UNPAID)이 남아 탈퇴 불가 */
  UNPAID_PAYMENT_EXISTS: "UNPAID_PAYMENT_EXISTS",

  // 비밀번호 재설정
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_CODE_ATTEMPTS_EXCEEDED: "RESET_CODE_ATTEMPTS_EXCEEDED",
  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",

  // 프로필 수정 진입 이메일 인증 (비밀번호 재설정과 별개)
  INVALID_PROFILE_EDIT_CODE: "INVALID_PROFILE_EDIT_CODE",
  PROFILE_EDIT_CODE_EXPIRED: "PROFILE_EDIT_CODE_EXPIRED",
  PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED: "PROFILE_EDIT_CODE_ATTEMPTS_EXCEEDED",
  PROFILE_EDIT_VERIFICATION_REQUIRED: "PROFILE_EDIT_VERIFICATION_REQUIRED",

  // 견적 요청
  ACTIVE_REQUEST_EXISTS: "ACTIVE_REQUEST_EXISTS",
  NO_ACTIVE_REQUEST: "NO_ACTIVE_REQUEST",
  TARGET_LIMIT_EXCEEDED: "TARGET_LIMIT_EXCEEDED",
  ALREADY_TARGETED: "ALREADY_TARGETED",

  // 견적
  ESTIMATE_LIMIT_EXCEEDED: "ESTIMATE_LIMIT_EXCEEDED",
  ALREADY_ESTIMATED: "ALREADY_ESTIMATED",
  NOT_SERVICE_REGION: "NOT_SERVICE_REGION",
  ESTIMATE_ALREADY_PROCESSED: "ESTIMATE_ALREADY_PROCESSED",
  /** 결제는 이사가 끝난(COMPLETED) 견적만 할 수 있습니다 */
  ESTIMATE_NOT_COMPLETED: "ESTIMATE_NOT_COMPLETED",
  /** 이미 결제한 견적입니다. 중복 클릭·동시 요청도 이 코드로 돌아옵니다 */
  ALREADY_PAID: "ALREADY_PAID",
  /** 결제 금액·주문 번호가 견적과 다르거나 토스페이먼츠 승인이 거절됐을 때 */
  PAYMENT_FAILED: "PAYMENT_FAILED",
  /** 기사님의 결제 요청은 견적당 1번만 보낼 수 있습니다 */
  PAYMENT_REQUEST_ALREADY_SENT: "PAYMENT_REQUEST_ALREADY_SENT",
  /** 선수금을 받는 단계(확정 + 선수금 설정됨)가 아닌 견적 */
  DEPOSIT_NOT_REQUIRED: "DEPOSIT_NOT_REQUIRED",
  /** 선수금 결제 기한(확정 후 48시간)이 지났습니다 */
  DEPOSIT_EXPIRED: "DEPOSIT_EXPIRED",
  /** 잔금은 선수금을 낸 뒤에만 결제할 수 있습니다 */
  DEPOSIT_NOT_PAID: "DEPOSIT_NOT_PAID",
  /** 추가 금액은 견적당 1번만 요청할 수 있습니다 */
  EXTRA_CHARGE_ALREADY_REQUESTED: "EXTRA_CHARGE_ALREADY_REQUESTED",
  /** 추가 금액이 견적 금액의 20%를 넘습니다 */
  EXTRA_CHARGE_TOO_LARGE: "EXTRA_CHARGE_TOO_LARGE",
  /** 응답할 추가 금액 요청이 없습니다 (요청한 적 없거나 이미 응답함) */
  EXTRA_CHARGE_NOT_PENDING: "EXTRA_CHARGE_NOT_PENDING",
  /** 추가 금액 요청에 먼저 응답해야 잔금을 결제할 수 있습니다 */
  EXTRA_CHARGE_PENDING: "EXTRA_CHARGE_PENDING",

  // 리뷰
  REVIEW_ALREADY_CONFIRMED: "REVIEW_ALREADY_CONFIRMED",

  // 찜
  ALREADY_FAVORITED: "ALREADY_FAVORITED",

  // 채팅
  /** 이사 완료 후 14일이 지난 방 — 지난 대화는 볼 수 있지만 보낼 수는 없습니다 */
  CHAT_ROOM_CLOSED: "CHAT_ROOM_CLOSED",

  // 공통
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  /** 봇 검증(Turnstile) 토큰이 없거나 틀렸을 때. 위젯을 다시 풀고 재시도하면 됩니다 */
  BOT_CHECK_FAILED: "BOT_CHECK_FAILED",
  /** Serializable 트랜잭션 재시도를 모두 소진했을 때. 잠시 후 재시도하면 됩니다 */
  CONCURRENT_REQUEST_CONFLICT: "CONCURRENT_REQUEST_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
